import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Layout from "./components/Layout";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Moulvibazar Govy. high School",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex flex-col min-h-screen">
        <main className="w-full max-w-[1000px] mx-auto bg-white shadow-lg border border-gray-300">
          <Layout>
            {children}

            <Toaster
              position="top-right"
              toastOptions={{
                duration: 5000,
                removeDelay: 1000,
                style: {
                  background: "#363636",
                  color: "#fff",
                },
              }}
            />
          </Layout>
        </main>
      </body>
    </html>
  );
}
