import {
  Geist,
  Geist_Mono,
  Noto_Sans_Bengali,
} from "next/font/google";
import "./globals.css";
import Layout from "./components/Layout";
import { Toaster } from "react-hot-toast";
import Hero from "@/components/Hero";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoSansBengali = Noto_Sans_Bengali({
  subsets: ["bengali"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-noto-bengali",
  display: "swap",
});

export const metadata = {
  title: "মৌলভীবাজার সরকারি উচ্চ বিদ্যালয়",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="bn"
      className={`${geistSans.variable} ${geistMono.variable} ${notoSansBengali.variable} h-full antialiased`}
    >
      <body className={`${notoSansBengali.className} flex flex-col min-h-screen`}>
        <main className="w-full max-w-[1080px] mx-auto bg-white shadow-lg border border-gray-300">
          <Layout>
            <Hero />
            {children}
            <Toaster
              position="top-right"
              toastOptions={{
                duration: 5000,
                removeDelay: 1000,
                style: {
                  background: "#363636",
                  color: "#fff",
                },
              }}
            />
          </Layout>
        </main>
      </body>
    </html>
  );
}